package it.randomtower.infiltration.model.actor.tag;

public enum TagEffect {

	NONE, PHYSICAL_BONUS, SOCIAL_BONUS, MENTAL_BONUS, PHYSICAL_MALUS, SOCIAL_MALUS, MENTAL_MALUS, CORRUPT_RESIST_BONUS, CALLING_RESIST_BONUS, MANIPULATION_RESIST_BONUS

}
